### ISSUE TITLE
Consider alternative formats for download of search results

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#104]
See #103 for creation of a FreeBMD1 format.

For consideration in a future release: adding alternative(s) to the FreeBMD1 format.

**Comment by DeniseColbert** [comment]
Any download should be limited to a useful number to researchers but not so many that it makes it easy for users to take a significant number of our records for 'other purposes'.

**Comment by richardofsussex** [comment]
OK, the ability to download search results as GEDCOM has now been added. 

I have used the same logic (i.e. stolen @Vino-S's code) as for the CSV download, which means that what is output is the current 'page' of results, in the currently selected order. If we want to impose a global limit of say 50 records on downloads, that will have to be applied to all download formats.

Another issue which cropped up is that the GEDCOM header includes the name of the person creating this GEDCOM. I have set it up so that if the person is logged in, their forename and surname are used. If they are not logged in, an entry which says in effect 'anonymous person' is created instead. (This needs to be tested.) If we want to, we can insist that the user _is_ logged in, so that 'anonymous' downloads can't be created. Decision needed ...

This code is now on test3.
