### ISSUE TITLE
Ensure test groups include those with variety of accessibility issues

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeBMD2#106]
After discussion on how we show results as viewed, wider discussion on our testing process and more detail relating to 'tiers' of accessibility. We need to ensure we have people from a variety of those tiers testing and feeding back so we can make the site as accessible as possible.

**Comment by richpomfret** [comment]
@neslihanu I've assigned this one over to you. It would be brilliant if you get a chance to review where @avielbassalian-freeukgen got to with this..

**Comment by neslihanu** [comment]
I talked to Aviel regarding this task. Here is the update;
In summary, he didn't do anything for that because A) He didn't have the means to find these people to test with and B) testing with these people isn't neccessary to meet WCAG accessibility standards. He recommended using  online testing tools to meet WCAG AA. 

If you  think we need these people to test with, you can send out a questionnaire to the mailing list that Denise and Aviel put together. Ask for anyone with disabilities to categorise themselves so that you can contact them directly.

**Comment by richpomfret** [comment]
Thanks @neslihanu (and indeed @avielbassalian-freeukgen). That sounds fine for now - I'll create a separate story in regards to testing using WCAG tools, keep this in mind when we roll out to a closed and indeed open beta group. We can close this one.
