### ISSUE TITLE
Create/Design "Add a Postem" page 

### ISSUE THREAD

**Issue by neslihanu** [FreeUKGen/FreeBMD2#131]
Create/Design "Add a Postem" page 

Please check below link:
https://www.freebmd.org.uk/cgi/CreatePostem.pl?d=bmd_1564415191&r=148453575

**Comment by KatyMawhood** [comment]
@PatReynolds What's the status on this?

**Comment by KatyMawhood** [comment]
@PatReynolds The link (above) is no longer working. Do you have an example of this page? Am I right in thinking it should be linked to each detail?

**Comment by PatReynolds** [comment]
@KatyMawhood This story could be achieved within the page created by bringing across https://www.freebmd.org.uk/postems-help.html (story #133)

Or it could be a sub-page.

The page to bring across may be generated in a way that makes giving a link to it not work properly ... please go to the detailed results page and click the link you find there to 'add a postem' "
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/421da2a2-6604-4697-8ee1-2165b29f4a3a)

That should get you to the add a postem page.

@vino this is going to need you to write the code so the post-em is linked to the database.   I'll find out who you will need to talk in the FreeBMD team to in order to do this).

**Comment by Vino-S** [comment]
Ready to be tested on test2

**Comment by DeniseColbert** [comment]
Typed in postem text, this error returned:

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/f4710228-0f7b-4305-ace8-15b60e1b168f)

**Comment by Vino-S** [comment]
Fixed it. Ready to tested on test2 and test3

**Comment by PatReynolds** [comment]
tested - I think this can now be closed.

**Comment by Vino-S** [comment]
Code deployed to test3. So closing it
