### ISSUE TITLE
Place info from"Transcriber Details" page onto Detailed results page

### ISSUE THREAD

**Issue by neslihanu** [FreeUKGen/FreeBMD2#132]
Create/Design "Transcriber Details" page 

Link to this page is dynamic, reached from results page where the transcriber's name is hyperlinked to a page like this:

![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/9f9d38ff-df03-46c8-9c85-8ead8262e134)

**Comment by archerbarrie** [comment]
Links as given are dependent on the database and will go out of date and therefore be unobtainable. Please use screen shots instead.

**Comment by PatReynolds** [comment]
So a link such as https://www.freebmd.org.uk/cgi/transcriber.pl?s=8174&f=1788410&d=bmd_1586250123 is unstable?

I don't think screenshots are a viable alternative.  

What would be viable is a link to https://www.freebmd.org.uk/db-latest.shtml  and text 'you can find out more about this transcriber here'

**Comment by archerbarrie** [comment]
@PatReynolds  Yes, that is correct, although ephemeral rather than unstable. This can be demonstrated by clicking on the original link (in the post of 13th August 2019).

I don't understand why screenshots don't work (e.g. MonetizeMore use them a lot). Amost all links have the danger that the data will have changed (e.g. this is true of FreeREG citations).

**Comment by PatReynolds** [comment]
Hi @archerbarrie penny has dropped:  use screenshots on Github, not use screenshots in FreeBMD2.

**Comment by PatReynolds** [comment]
Potential to enhance - ask if people would like to join the volunteers (link to the Volunteer tab) and possibly repeat message about other ways to support from the Volunteer tab?

**Comment by PatReynolds** [comment]
Needs review - is it better for this information to appear in the Detailed Results (in the Transcriber slot) or a separate page (perhaps linked from Detailed Results by an icon in the More informatin slot.

**Comment by PatReynolds** [comment]
I'm personally veering towards having the transcribers name (if transcriber wants) and number of records they have transcribed) as part of the Entry information Page  - there is already a slot there, but not currently linked to the database.    What do you think @archerbarrie ?

**Comment by archerbarrie** [comment]
At the moment we provide the transcriber's name (if they agree) and number of records, but only as a link from the user id. Don't forget that there may be several transcribers for any one record. Without seeing what it would look like it is difficult to comment but it sounds like it might be rather cluttered. I don't think it is information that researchers would be interested in ... apart from wanting to get in touch with them because they think they are researching the records they have transcribed!

**Comment by DeniseColbert** [comment]
@Vino-S please develop so we can see the layout

**Comment by PatReynolds** [comment]
Sorry, @Vino-S didn't assign you to this - have now assigned you and taken myself and Denise off (temporarily)

**Comment by richardofsussex** [comment]
It would help to have a spec! BMD1 has this:
![image](https://user-images.githubusercontent.com/2197102/192822418-69518009-e632-430c-80e2-33b67b8f13a6.png)
Is the intention to replicate this within the single table cell provided, or to simply have the transcriber's ID?

**Comment by DeniseColbert** [comment]
To test on Test3

**Comment by DeniseColbert** [comment]
Transcriber info blank:
![image](https://user-images.githubusercontent.com/19173257/196624769-630b6dba-4198-4811-a9ad-79b01c2b1a4d.png)

@richardofsussex reassigned you to take a look
Checked several records, all blank

**Comment by richardofsussex** [comment]
Try searching for forenames "Ada Maria", exact match, all event types, 1837-1850. The first one (Ada Maria HARVEY) has a transcriber with a link to their name and no. of records transcribed. The eleventh (Ada Maria LEIGH) has two transcribers, both linked. The sixteenth (Corringham) has one. They are the only records in the first 20 hits with any transcriber info: I think that's a reflection on the test3 data, rather than my code.

**Comment by DeniseColbert** [comment]
All fine upon testing.

**Comment by DeniseColbert** [comment]
@Vino-S has this been deployed?

**Comment by DeniseColbert** [comment]
Done, closing
