### ISSUE TITLE
Decide how to handle SCAN facility / Create a page for SCAN

### ISSUE THREAD

**Issue by neslihanu** [FreeUKGen/FreeBMD2#138]
On FreeBMD1, SCAN details are shown on the "Detailed Result Page".

You can find the details below:

1) If an entry has a scan icon on the "Search Results Page", user can click on the icon and view SCAN details. When the user click on the SCAN icon, the user is navigated to the "Detailed Result Page/Entry Information" page.  And the user can view the original scan that was used to transcribe this entry. Please check this page (https://www.freebmd.org.uk/cgi/information.pl?scan=1&r=198612499:8983&d=bmd_1564415191)

2) If the user does not click on SCAN icon and he clicks on the INFO icon on the "Search Results Page". He is navigated to the "Detailed Result Page/Entry Information" page. But the page does not come with "Original Scan" info, there is a text and icon for scan which is " Scan available. Click here to view". If the user click on "View", the user can view the original scan on the "Detailed Result Page/Entry Information" page. Please check this page and click on view. (https://www.freebmd.org.uk/cgi/information.pl?r=198612499:8983&d=bmd_1564415191)

So, a design/solution should be considered for SCAN feature. I believe we can create a separate page for SCAN, where can include below details. There are many pages about SCAN on FreeBMD1, I believe we can combine those. Those are what I found at the moment:

- Scan help:  https://www.freebmd.org.uk/scan-help.html
- Scan Information: https://www.freebmd.org.uk/cgi/scan-response.pl?y=1949&q=1&e=3&a=find&d=bmd_1564415191&r=Colbert%7CJack%20E%7CChatham%7C5b%7C549&signature=drGENzbp9v4ejfVO3OO9Xg&extra=ANC-05%2FA-F,202
 - A link for feedback: https://www.freebmd.org.uk/cgi/information.pl?r=198612499:8983&d=bmd_1564415191&;force=1&scan=1 

When the user clicks on feedback link, "Detailed Result Page/Entry Information"  page comes with below text and CONFIRM & REJECT button.

"However, because of limitations in the data we have available we have not been able to determine with complete certainty that this scan contains the entry.

You can help future researchers by reporting whether a scan does or does not contain the entry by using the buttons below after you have viewed the scan. Use Confirm if the scan does contain the entry and Reject if it does not. Note that in order to protect against mis-use of this facility you can only report on the last scan viewed and you must do so within 20 minutes of requesting the scan.

Please do not use the Reject button to indicate that the record has been incorrectly transcribed, rather use the correction process described above."

OR, we can design in the same way. When the user clicks on SCAN, "Detailed Result Page/Entry Information"  page comes with SCAN details. 

@PatReynolds I would appreciate if you could review and share your ideas on this issue.

**Comment by archerbarrie** [comment]
Some background to this facility may help.

Unfortunately when the project started it was not perceived as necessary to have a consistent naming scheme for scan files. Latterly when we wanted to give access to the relevant scan a good deal of work had to be put into interpreting the scan file names and enabling the scans to be linked. We cannot get this 100% right but it is probably at over 95% (at the time of implementation it was suggested that it might be 0% right!). As a result of this a system was put in place to allow corrections to be submitted by users and this improves the linking.

The user feedback was implemented before AJAX and should now be done with pop ups.

It has been noted that the information page only contains the scan link if the user clicks on the scan icon. This was done because it was felt the extra cost of finding the scan should only be incurred if the user explicitly asked for it. The overhead is actually not significant (certainly not nowadays) and so in FreeBMD2 I would suggest the information page should always contain the scan.

The scan help and the scan response are addressing different issues and I don't think they should be combined.

**Comment by PatReynolds** [comment]
Thanks for this, Barrie - very helpful!  I like the idea of presenting the image on the information page (the detailed results page). do we show all the images, or just one of them (allowing the user to call additional images, if wanted)?

We have a comprehensive user feedback system (currently undergoing some revision) which allows feedback on data issues, 
There is a "Report an Error in this Data" button on the detailed results page - i.e. submitt a correction
There is also a Contact us form which allows submission of
Data Question
Website Problem
Volunteering Question
Genealogical Question
Enhancement Suggestion
Thank you 
General comment

The work we are doing at the moment on this part of the system is to include FAQ that will, we hope, cut down on the number of contacts recieved - e.g. by directing Genealogy Questions to our Facebook groups, GENUKI and other resources, and saying we don't answer Genealogy Questions.

I suggest we add an "Report an Error in this Image button" by the image.  Does that seem good to you @archerbarrie ?

**Comment by archerbarrie** [comment]
Just to clarify, what I was suggesting was the scans would be accessible from the Information page (as FreeBMD1) not that the Information page would contain the image of the scan, which is what @PatReynolds seems to be suggesting. This is what it looks like on [FreeBMD1](https://www.freebmd.org.uk/cgi/information.pl?cite=mO93vKV%2BHkZmupplvEHZWg&scan=1)
![image](https://user-images.githubusercontent.com/14543258/71045676-c1fc3e00-212d-11ea-95c4-750f83320be5.png)
So the user selects the scan they want to view (the first is already selected) and then clicks on "View the Original". I have used the above as an example because it illustrates some (but not all) of the complexity of displaying scans.

I would comment on "directing Genealogy Questions to our Facebook groups" that in the past we have run into trouble with similar actions, when we directed certain requests to a mailing list. The issue was that it was not made clear that the request would be made public and I believe the same is true here.

I don't like "Report an Error in this Image button" (sic). "Report an Error in this Data" means that we will examine the report and correct the error if necessary. By implication "Report an Error in this Image" would do the same for an image but this is NOT what we (currently) do. By using Confirm/Reject the users themselves effect the correction - we take no (manual) action. Now, of course, FreeBMD2 could go down a different route but we should very seriously consider the staffing implications of having a team correcting scans. (We used to have a "team" managing corrections but it got out of hand and we had to automate it.)

**Comment by archerbarrie** [comment]
I previously mentioned the amount of work necessary to identify a scan as the reason the scan selection is only displayed if you click on the scan icon in the search results and not if you just click on the Info button. I now recall that it was also the fact that the information can be long and quite involved, as illustratrated in the example in the previous post, and therefore should not be displayed unless the user has asked for it and is, therefore, expecting it.

**Comment by PatReynolds** [comment]
I'm suggesting the link to the image is from 
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/cd4c637d-d656-4eba-91ce-5e4abbc69375)
and is probably better _as_ the image - putting alternate images and information about images on another page (with a link in the 'image' column) seems to me to be a good way to present the information.

I.e.ot from 
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/c1d2d19c-7746-4ca8-afae-67a40e926e03)
the search results page should give enough information for the reviewer to decide which records are worth looking at in more detail.

**Comment by archerbarrie** [comment]
@pat I am trying to unravel your comments but I am having some difficulty. 

What does "and is probably better as the image" mean? You want an entire scan as the link? 

What is the "image column"? Possibly the one with the header "Scan"? It should be noted that the scans found are associated with the search result, not the individual transcriptions. Hence having a Scan column is superfluous and misleading since each transcription would take you to the same scan.

The use of the term "alternate images" worries me. This implies there is an image which is the actual one used and then there are others. This is incorrect. The data often does not identify a single scan so basing the design on that assumption is not a good idea.

Also I worry that decisions are being made on an incomplete display of the information available, that is the data for this entry in FreeBMD1 is
![image](https://user-images.githubusercontent.com/14543258/72279561-4a3b0980-362e-11ea-95b3-43bd467e546f.png)
which shows there are two transcriptions not just the one shown.

Finally, your last sentence implies that all information from the index should be displayed in the search results. At the moment Volume and Page are missing as are indications of Postem, Comment, System Entry, etc. I had assumed that a decision had been made not to display this information.

**Comment by PatReynolds** [comment]
Hi @Barrie.

Current proposal is:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/e287f096-e22c-4489-8b01-995269e088a8)
with something to be decided (maybe an icon) under the 'scan' where there is something to show, this will link to a Scan page which combines this part of the Entry Information page with the Help relating to Scans (https://www.freebmd.org.uk/scan-help.html):
![image.png]
(https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/47dccf35-dae0-4e94-a84b-793784be9ac7).

Personally, on this new Scan page, I would like to see at least one of the images for the record - without having to click anything else.  

The thinking behind not having a link from the list of matching entries is that the list is already very full of information, and we want to remove any that does not help a researcher decide whether or not to see the detail of a record.

I hope that helps and you can provide feedback on the proposal.

**Comment by archerbarrie** [comment]
@PatReynolds I am bemused by the FreeBMD2 design process (to put in mildly). You say "The current proposal is" but all that shows is a small part of page - it is in no way a complete proposal (e.g. Postems, corrections, comments, system entries, late entries, ec.). I don't understand how you decide on  how you access scans without putting it in the context of the overall page design (which does not exist).

And please note that I have already commented in this thread that there are serious mistakes with even the design that has been done, for example the scan applies the the search result not the transcription.

You say "we want to remove any (information in the search results) that does not help a researcher decide whether or not to see the detail of a record" but one of the main reasons for looking at this page is to see the scan, so requiring an extra click and page transition (as you are proposing) is a retrograde step. There are numerous places in the (totality of) help information where we say "click on the spectacles icon" (which indicates there is a scan). So not having that indication in the results is an ergonomic minus for FreeBMD2. If you have that indication you can use clicking on that to display the scan information, i.e. what FreeBMD1 does.

What do you mean by "I would like to see at least one of the images for the record - without having to click anything else". In order to be useful viewing the scan has to be in as large a window as possible since you are looking for a particular entry which you won't be able to read if the image is too small, resulting excessive scrolling (bear in mind that I have to search scans very often). Orginally we did use DejaVue to display the image but dropped that in favour of letting the browser do it and thus letting the user define how images are viewed. If you put the scan image on the scan page it will of necessity be very small and, as far as I can see, just decoration. Please explain more fully what you mean by your statement. We also need to consider whether it is feasible to view images on a small screen device (e.g. a phone) and whether we need to do anything special to enable this. For the reasons already explained, I doubt that it is realistically feasible.

**Comment by PatReynolds** [comment]
Have three images, side by side, so you can choose the best, and a click would take you to a mew page, zoomable and downloadable if you would like to.

How many images (maximum) does one event/record have?

**Comment by archerbarrie** [comment]
@pat So, this seems to be a different proposal and is basically thumbnails. Not sure how often you will see enough detail to be able to choose the best, e.g. 1909B1-A-0005
![1909B1-A-0005-thumbnail](https://user-images.githubusercontent.com/14543258/75306541-490e1680-5841-11ea-82fe-36fddbec46a5.jpg)
![1909B1-A-0005B-thumbnail](https://user-images.githubusercontent.com/14543258/75306654-98544700-5841-11ea-97d3-99aaea53b49c.jpg)

Note that with the number of scans we have I would suggest we could only create the thumbnails automatically.

Earlier in this thread I gave an example with four scans, but, with rescans, I guess six would cover most cases. Although I would hope we would not design a system with any limitation.

**Comment by DeniseColbert** [comment]
@archerbarrie The idea is to have images of the scans at the bottom of the page and large enough so that (hopefully) difference in quality is obvious. That may be possible at three scans abreast or they may need to be larger, at two abreast. What do you think?

**Comment by archerbarrie** [comment]
@DeniseColbert I think it sounds like an awful lot of work for a very marginal faciliity. There are 3.1 million scans and some (the handwritten ones) might be distinguishable for quality but many will not.  And if they are at the bottom of the page they will rarely be seen. But overall this is a poor way to go about a page design ... we do not have a proposal for what the Information page might contain, so such detailed discussions are taking place in a vacuum. Surely we should have a list of what could go on the page, then try to prioritise each item and then work out where each should go.

**Comment by PatReynolds** [comment]
@DeniseColbert could you ensure that @Barrie has access to the latest Figmas, please?  

@Barrie, if you filter by MVP (minimum viable product) you will see what we think needs to be included.  We have have to revisit this in order to get a version that can begin user testing (which will undoubtably refine the layout, as well as show what tools are more needed than others to be added.

**Comment by DeniseColbert** [comment]
@archerbarrie now has access to Figma

**Comment by archerbarrie** [comment]
@DeniseColbert What are my credentials for Figma? I have tried all I can think of without success.

At the moment all I can see (without logging in) are about 30 randomly distributed thumbnails. Although I have discovered I can zoom in this doesn't identify which is the MVP version.

**Comment by PatReynolds** [comment]
Hi @Barrie for clarification, does the transcription record contain a permanent url for the image it was transcribed from?

**Comment by archerbarrie** [comment]
@PatReynolds No. We don't have permanent URLs for scans.

**Comment by PatReynolds** [comment]
In light of the information, perhaps it is best to generate an image from the only/best source for the (detailed) information page?

Other images (or all, if thought better) would be as plain links (no need for thumbnails).

**Comment by Vino-S** [comment]
Hi  @PatReynolds ,
Following are my thoughts for this facility:
1. We cannot have a column for Scan in our Entry Information table as @ archerbarrie suggested.  Entry Information table according to our current design  has Transcription details( transcribers who transcribed the record.).  Since the Scan is associated with search result, it will be same for every Entry in Information Page.

2. We can make use of Report a Data Problem through multi-modal. But this requires re-design of Entry Information Page. The Corrections content can be replaced by `Report a Data Problem` button
![image.png](https://images.zenhubusercontent.com/5ca2316a45147541ad68a420/e17f0a28-14e5-4439-a41b-e2219533d81e)

3. `Report an Error in this Image button`: I am not sure about this to whom we are going to report and what action we are going to take with the report. Since its researcher feedback on scan image we can just provide two radio buttons to Accept or Reject.

4. We can show the image of the scan in the  Information Page. However considering the limitations mentioned by Barrie, I have following way  implementation.
1. Show thumbnails of Scan file
2. When researcher clicks on thumbnail, they can view larger image  with functionality of Zoom on cursor position.

5. We also have to show the Postems for the Entry, so a simple text on Postem would not be enough.

I had re-designed the Entry Information page, however its still Raw stage. I can  show a demo in our meeting or push the changes to test.

**Comment by archerbarrie** [comment]
Could I ask a simple question. What are we trying to achieve by showing a thumbnail of one of the scans? Currently FreeBMD shows a thumbnail but it is of a generic scan (and is overlaid by "View the original"). Generating thumbnails of the scans is a lot of work (and is a continuing process since scans can and do change) so we need to ensure that there is actually some benefit. 

@PatReynolds suggested it was a thumbnail of the "best scan" but we don't know which one that is. In addition, as I have [pointed out](https://github.com/FreeUKGen/FreeBMD2/issues/138#issuecomment-566816307), especially with composite scans, the list of scans can get quite complex, and which one we display is difficult to determine. 

@Vino-S seems to be suggesting we show a thumbnail of each of the available scans. It is not uncommon to have multiple scans, so we would be talking about quite a lot of screen real estate. At best one might be able to determine that the thumbnail is of a scan that is hand written or typed, so that has a tangible, if slight, benefit.

**Comment by archerbarrie** [comment]
@PatReynolds You [suggested](https://github.com/FreeUKGen/FreeBMD2/issues/138#issuecomment-591398874) that in Figma I should "filter by MVP" to see the current information page proposal. The only information I can see in Figma is for search and I cannot find any filter facility.

**Comment by PatReynolds** [comment]
@DeniseColbert can you let @archerbarrie know how to see the MVP designs on Figma, please?

**Comment by KatyMawhood** [comment]
@archerbarrie I've recently started volunteering in UX design with @Daniel-silve1ra. 

We're currently working to progress the "Search", "Results" and "Detailed Results" for both desktop and mobile layouts. Evidently, there's some significant work that proceeds us. 

@richpomfret @archerbarrie @DeniseColbert @Vino-S  It sounds like the SCAN facility is a specific feature of the detailed results page awaiting UX updates. It also sounds like Raw designs are being implemented/tested, in the absence of UX updates. 

Would the UX team getting involved in this stage be helpful or unhelpful?

**Comment by archerbarrie** [comment]
@KatyMawhood Just to clarify: I am not part of the FreeBMD2 team. My time is pretty much fully taken up with FreeBMD1. Nevertheless I have tried to give some input to FreeBMD2 by relating what users can do in FreeBMD1 and what information is in the database.

So, as an outsider it would seem to me to helpful to decide what the overall UX should be before implementing the interface ... but that seems to be rather old fashioned nowadays.

As regards the SCAN facility ("View the Original" in FreeBMD1), this has previously always been considered a relatively minor facility, albeit important, as far as users are concerned ... only about 3% of searches result in the use of the facility. In FreeBMD2, however, it seems to be causing a lot of angst.

**Comment by KatyMawhood** [comment]
@archerbarrie Thanks, that's a really helpful overview. I agree that an overall UX should be tackled before implementing the final UI. 

@richpomfret Whilst this is clearly an important feature, it sounds like this isn't an MVP for FreeBMD2. It's listing as a "high priority" story doesn't seem to make sense if it is only used by 3% of searches, especially when we are still focussing on the core layout of the pages.

Should this be returned to the backlog, or is there a better place for this to sit whilst we progress the assigned UX tasks?

**Comment by richpomfret** [comment]
Agreed (in principle) to add this functionality within the 'detail' page of the search results.

Pat added: decision was to add thumbnails (subject to test of this) with user being given options to download, and to open in a new window, if they prefer.

**Comment by PatReynolds** [comment]
@Daniel-silve1ra and @KatyMawhood  I have put examples of scans placed in the 'examples of scans' folder in UX in FreeBMD2.

There are four events (births, marriages or deaths) all with at least two scans, one with three (one of those a rescan of another from the same source.

You should be able to work out the pairs from the year, which is part of the file name, to see whether thumbnails are sufficient to give a judgement of quality (and if so, what size thumbnails.

Many thanks,

Pat

**Comment by KatyMawhood** [comment]
@PatReynolds That's great and all looks good. Thanks!

**Comment by archerbarrie** [comment]
Well, obviously three events not four. I would be interested to know what scans are being used for evaluation but I don't have access to FreeBMD2/UX. There are numerous different formats of scan and I would be surprised if 7 scans was going to be sufficient to draw any reliable conclusions.

**Comment by PatReynolds** [comment]
Hi @archerbarrie the aim is to have a selection of varying quality, to see what size of thumbnail is needed in order for a user to be able to select one to view. If you know of some "known to be horrendous" quarters / scans it would be good to have an example or two of these (and their better counterparts).

**Comment by archerbarrie** [comment]
@PatReynolds @KatyMawhood I have uploaded a number of scans, including a pair (1964M1) in the "quadrant format" which did not have a sample. In reality it is not the quarters that have poor quality scans but the quarters where the different sources are markedly different in quality that need to be addressed.

**Comment by PatReynolds** [comment]
To be implemented as part of #138, so closing now.

**Comment by richpomfret** [comment]
Discussed 'tiling' the scan images when there are 3 or more.
