### ISSUE TITLE
Reduce space between record types

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#158]
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/c8d881c1-4280-483f-ad83-8384be271266)

**Comment by Vino-S** [comment]
Is it still a requirement. The search-form uses a grid system and will not be achieved easily.

**Comment by DeniseColbert** [comment]
To be revisited when changes for mobile are considered

**Comment by DeniseColbert** [comment]
@KristinaGadzhieva FYI

**Comment by DeniseColbert** [comment]
@Vino-S to look into reducing space between checkboxes/events and investigate placing them horizontally below the name/date fields row.

**Comment by richardofsussex** [comment]
Comparing with FreeReg, that has a simple set of radio buttons. What is the effect on the code if we simply 'borrow' this design? Is it complicated by the fact that various input elements are displayed or hidden, depending on which record type/s have been selected? @Vino-S to comment, please.

**Comment by AlOneill** [comment]
@richardofsussex 
See also my suggestions in #490 for fixing the **misuse of HTML labels for dates** and the **spacing of event types** by using classes in freereg_content.css (that BMD was using when I checked last). These are Accessibility issues as well as aesthetic ones.

**Comment by richardofsussex** [comment]
Thinking about it, the current design allows the searcher to select two of the options (e.g. 'births and deaths'), which the radio button solution would not.

The excessive vertical space is caused by a CSS rule for **.search_form li** which specifies a bottom margin of 25px. This is clearly not the intended outcome, as this **li** element is several levels down within the search form. If I add a **style** element which overrides this rule by specifying no bottom margin for a **li** at this level:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk03QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2802a9a13faf71ca509a02abeb49e7fa601536a/image.png)

then the space between the check boxes is greatly reduced:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDg3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--552843662650c7fd2bd146dcca33015edb153fa1/image.png)

**Comment by AlOneill** [comment]
@richardofsussex 
The markup pattern of **field-set and legend**, as used on REG, can be used with check-boxes as well as radio-buttons: it improves Accessibility as well as aesthetics.

**Comment by richardofsussex** [comment]
@richardofsussex to check @AlOneill's comment and feed back required changes to @Vino-S

**Comment by richardofsussex** [comment]
As far as I understand it, @Vino-S has already implemented this pattern in test3, so in my view this issue can be closed and the code moved to beta.
