### ISSUE TITLE
DT: Decide upon/write text for HELP page

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeBMD2#172]
Decide what to add in the Help page. Does the FAQ go here or in About?

Do we use the text here (https://www.freebmd.org.uk/search-help.shtml) and update it (including screengrabs)? What else, if anything?

**Comment by PatReynolds** [comment]
Spreadsheet created (https://docs.google.com/spreadsheets/d/1A0J52BvWjFx0gRHyyjPjhr-LPN3mazxVTQvBQT97ZSw/edit?usp=sharing) , work now undertaken by documentation team 16/2/20202

**Comment by PatReynolds** [comment]
Comfort to email Pat a draft text to the team at groups.io.

**Comment by ComfE-2662** [comment]
Sorry I didn't get round to making the draft for this. 

I have just read it and it felt like I was reading the Torah (I don't speak Hebrew).

There were rules and dependencies like using a backslash or a question mark or both, One * or two **, dashes, hypens, options to write the in 3 different ways (?), links to pages which involved even more reading.

I tried some of the functions on the test3 page and got no results. Some I didn't know if i was getting different results or not.

The only thing I can suggest with writing this draft is that I rewrite it how I think it should work, logically inside my head. I would take out all the 'if you want this, then you could do this or that or this' and change it to 'to do this, then do that'. So basically write it up how I thik it would make sense to work then this could be used as a guide for the development team to make it in this way. 

Otherwise I'll wait for the docs team to get back to me about what actually needs to be kept and make a draft based on what they say; I have posted in groups.

**Comment by PatReynolds** [comment]
Yes, write a 'basic' version as you suggest - there should be a secondary help page that is for help on the advanced tools that more experienced users will find useful.

**Comment by ComfE-2662** [comment]
I've been trying to work on this job and Philip has advised that there are edits in a tree somewhere on Refinery and that it is advisable to check them for guidance. 

Please can anyone give me access to Refinery. 

I will need this access if I am to do other work, not just this one. 


![Capture.PNG](https://images.zenhubusercontent.com/5ecd15a9812f89eaa03d991e/39e99c83-5898-4206-80d2-55e50f62f1c4)

**Comment by ComfE-2662** [comment]
Ok, so as mentioned, I spoke to Alison and Philip about this in the groups.io chat and Philip told me that on Refinery on test3 there are some edits that @PatReynolds has made for this page and it would be wise to check those edits before I go ahead and make my own. 

@AlOneill on the other hand mentioned that the page is difficult to read especially if someone has a screen reader because of the 'here', 'here' and 'here' mentioned throughout the text. It is best if the word itself is hyperlinked rather than 'find more information 'here'' 

So with this info, I kept the edits to just following Alison's advice of getting rid of the 'here' But until I have access to Refinery, I won't be able to include the edits that Pat would like for this page. Unless someone can find the edits that Philip is talking about and maybe copy and paste them in a document for me. I don't want to do double work and it would be so useful if I could get into Refinery. 

Nevertheless, I have gone through the page and crossed out the 'here' instead, I have used blue < and > to show which word should be linked. The links are still in the document, they're are just crossed out. 

The biggest issue with the document, apart from the fact it is very wordy, is that it is written in the passive voice. So for example it says: 
“A list of which part of the country is covered by each volume is given 'here'.”   
(The 'here' is hyperlinked)

When really it should say: 
"Each volume is covered by a 'list' showing which part of the country." 
(The word 'list should be hyperlinked)

This made it kind of difficult to edit and take out the 'here' and it still make sense. 
Anyway, before I go any further, I would really like to see the suggested edits by Pat in Refinery if any one can access them. 

In the meantime here is the link to the draft that I have made:
[https://drive.google.com/file/d/1mZACvsL_noCn6mGUUlb80vKvRJHJ3CzW/view?usp=sharing](url)

**Comment by PatReynolds** [comment]
Hi @ComfE-2662 my edits ( I added the section about Citations) were already in test3 - I think you meant test3, not test 2 (which we no longer use).

I will download what is in test2 so you can access it.

**Comment by PatReynolds** [comment]
I moved things in test2 to test3 which were not already there.

For both Help and About I think some thought is needed on structure - what needs to go into the top level page, and what is better on a sub page - either on its own, or in a group.

**Comment by ComfE-2662** [comment]
Yep, that's what I said, in Refinery on test 3 . I only have access to test 3 anyway haha! But it's getting to actually see these edits which I am having trouble with because I can't get into refinery. 
Unless you mean they are somewhere else in test3? 

But anyway, a download would be super useful, thank you. Then I can recreate another draft using that. 

So are you saying I should try and split up the topics as such, into a main page and a sub page? Any guidance on structure would be great.

Also did you read the part where I have changed all the 'here' links? What do you think about that?

**Comment by AlOneill** [comment]
@ComfE-2662 
Sorry, I did not explain **link-text** at all well! I'll try again.

"Here" is not good link-text: it conveys no meaning and there are a number of links on the page that all have exactly the same link-text, yet they point to different things/places. I did not mean for you to necessarily remove the word, "here", but to use or create a suitable phrase for the link instead of "here". The **link-text should be meaningful and unique**.

And "list" is almost as bad :-) — list? of what?

Dealing with the passive voice at the same time, how about something like:
"This list shows {which volume covers which part of the country}."

The link text is in the curly brackets. Now a **screen-reader user** will be able to identify it in a list of the links on that page. That is a common way of navigating for someone who cannot see the page well enough to read it themselves, so they get the computer to read it out to them. The software can also read a list of only the links, i.e. just the link-text.

**Comment by ComfE-2662** [comment]
Thanks Alison, this clarifies a few things.

Do you know of these citations that Pat has done?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by richpomfret** [comment]
@AlOneill just in case you missed the question above.

**Comment by AlOneill** [comment]
@ComfE-2662 I'm not the best person to answer your question about citations. There are several pages on test 3 that have some/all of the "Help with citations" text. I'm really not sure which page(s) @PatReynolds meant you to look at.

The original full version of the text is on the [DRAFT Help with citations](https://test3.freebmd.org.uk/cms/help/draft-help-with-citations) page, but I can see that Pat has put parts of it in a couple more "Help" and "About" child pages too.

**Comment by PatReynolds** [comment]
I will start a new story for improving links as this needs doing for all pages.  This page also needs CSS / header etc (as do many, but content is now ready for proof-reading.

**Comment by PatReynolds** [comment]
@PatReynolds to ask proofreaders

**Comment by PatReynolds** [comment]
Proofing document needs revision.

**Comment by PhilipClarke712** [comment]
@PatReynolds 

Sorry to split hairs. That page is **not** a draft page and it appears to have been created up copying and pasting sections from the various sub-pages that sit below it: so information is duplicated and it has almost no hyperlinks to other pages / subpages.  

I'm not allowed to work on such pages, I cloned a copy of the page which is prefixed DRAFT - and is suffixed (W-i-P). It is the Draft page, or another draft page, that needs to be (possibly reworked and) proof-read, in conjunction with its subpages, and then put through the signing off process. I'm working on the draft Transcriptions page and its sub-pages at present.

**Comment by PhilipClarke712** [comment]
Hi @PatReynolds ,
I looked at this page this morning and ran it through the spell-checker, etc. and as it stands it is not a bad page at all (Glaswegian for "good").

I did some Volume searches on test2 (not implement yet on test3) and it works. Note: I do Volume searches myself, but I use Brett Langston's "Handbook to Civil Registrations Districts" (2nd ed). I don't beleive that we have the mapping that is claimed (without being linked) on FreeBMD2. 

FreeBMD(1) has District to county mappings, and district to volume mappings (all of these relationships change over the last 180-ish years of GRO).  We _could_ throw those files into e.g. a spreadsheet and make a new mapping, but we offer nothing comparable to Brett Langston's book or his pages on UKBMD. So that section of the Help page will need modifying.

For a short-implementation solution, I've cloned another copy of the page which is currently on test3 called DRAFT - Help (edited copy)  - DRAFT and I will add live hyperlinks to external sites and to non-draft FreeBMD pages and add [link-text = ] [ link =] for draft-pages. That can be done in a day-or-so and send it for sign off. That will provide a lot the functionality of FreeBMD that most users need.

Note: for the short to medium-term I have another draft: there is extensive duplication between the Help pages and it's sub-pages: so the way out might be to _trim_ the sub-pages and have the second draft linked to the trimed-subpages (which the current Help and and my intended draft-Help page does not link to). But, we don't have a finished Transcriptions page yet.

**Comment by PatReynolds** [comment]
Thanks, @PhilipClarke712!  I am assigning you to this story now, taking myself off (but do ask if you need anything) - move to Needs review when ready.

**Comment by richpomfret** [comment]
@PatReynolds and @PhilipClarke712 can we close off this story? Have we agreed/decided upon what HELP page text we will provide initially for MVP and then beyond?

**Comment by PhilipClarke712** [comment]
Hi @richpomfret  @PatReynolds , @AlOneill 
  I have a page - which I think is complete in respect of what test3 can currently do - https://test3.freebmd.org.uk/cms/help/draft-help-1st-interim-version. 

It will be going to Alison in the next five to ten minutes.

So, I would suggest that this story can be closed.  I might have to raise a new story if the page is considered in need of major change.

**Comment by PatReynolds** [comment]
Many thanks, Philip, moving to ready for user testing prior to closing in Scrum.

**Comment by AlOneill** [comment]
@PatReynolds The current Help page has never been signed off for HTML and other technical stuff; I'm working on Philip's draft — there is quite a lot to fix.

Which page exactly do you consider Ready for User Testing?

**Comment by PatReynolds** [comment]
This is the 'decide on the text' not 'implement the text - that is still a live issue  (#173 ) and is not ready for testing.  This story is 'ready for closing after confirmation in scrum' rather than 'ready for user testing', but we don't have a column for that.
