### ISSUE TITLE
Systematic review of Info button content

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeBMD2#185]
Could not find a logical place on which to provide systematic feedback so created this one

**Comment by Captainkirkdawson** [comment]
1. Info button on on Forename. a) Needs to explain what "Exact match on first names" does in light of the text that says latin and and abbreviations are done. Does it simply disable those or what? b) Do we need to comment of multiple names?
2. Info button on Surname. a) need to comment it is optional  b) Current info text has formatting visible c) Need to add something on Phonetic option 
3. Info button on Date Range Start and End a) Says select month when really one is selecting a quarter ending in the month
4. Info button on Date Range End say no selection uses end date. **It is actually using start date so if both are left empty you will get no results.**
5. Info button on spouse forname.Needs to explain "Identifiable spouses only" option. I have not the slightest idea what it means. Does it apply to just the forename or surname or both?
6. **If you select birth and marriage record types you cannot enter name in the Souse/mother field. It is blocked yet the name should be valid for both**
7. The spouse forname is always open to entry.
8. info buttons for volume and page are empty
9. Info buttons for county and place  have wrong information forename and surname
10. **Surely the District list should be connected to the county ie if one selects a county the list of districts should reflect that county and not remain as a complete list**

**Comment by Vino-S** [comment]
Hi Kirk,
Fixed _7. The spouse forname is always open to entry.
The spouse forename field is now enabled for only marriage records.

Fixed 10._Surely the District list should be connected to the county ie if one selects a county the list of districts should reflect that county and not remain as a complete list_
The Districts are now populated dynamically

8 and 10: corrected info icon of counties and disticts. Though it just says optional.

4_. Info button on Date Range End say no selection uses end date. It is actually using start date so if both are left empty you will get no results._ Set End date to 1992

**Comment by Vino-S** [comment]
For all the info icon text we need something short and helpful. the FreeBMD1 has fully explained help page which I used for back-end development. But I am having hard time in summarizing it for info icon text.

**Comment by Vino-S** [comment]
Explaination for Identifiable Spouses only option
From the year 1912 the marriage records contain Spouse's Surname. however not all spouse have been transcribed. So such spouses are unidentifiable since we cannot determine the Given Name.
Checking the Identifiable Spouses only will give records where there is an entry that the given name can be checked against.

**Comment by Captainkirkdawson** [comment]
Thanks @Vino-S the info buttons are a real challenge that's why I wonder about adding a context help link to any info text where additional information is needed and available. I say a context help link and not a general help link ie it goes to the exact place in the help where it is explained. Even with your explanation on 5 I am still totally confused

**Comment by Vino-S** [comment]
Yes Identifiable Spouse is bit confusing. I understood only after doing few searches.
I added a search image below for easy understanding. 
Below is an image of Marriage Entries on Page 1371
![image](https://user-images.githubusercontent.com/26073943/72242093-7039bd00-35e0-11ea-99ba-19eaac1e9bdd.png)

In the image we have three Spouse Surnames: Barnett, Lowe and Henriques

The Entry: Henriques Basil L C has a spouse Surname 'Lowe'. This Spouse surname 'Lowe'  is also present in the Surname column in the same page in a same quarter.
So we can say 'Rose L' is the spouse Given Name for Henriques Basil LC entry.

Similarly we say the same for Spouse surname Henriques. 
Basil L C as spouse Given Name for Rose L Lowe.

But Spouse Given Name cannot be determined for Priscilla Blaiberg whose spouse surname is Barnett.
Because we do not have any record with Surname Barnett in the page. So it is unidentified Spouse.

So when we search with identifiable spouse only option Priscilla Blaiberg entry will not be shown.

**Comment by Captainkirkdawson** [comment]
@Vino-S now that was a good explanation

**Comment by Captainkirkdawson** [comment]
@Vino-S point 7 The spouse forname is always open to entry.
 Sorry it it does not allow entry although it does open on Marriage. However if you do  revise search it permits input and display the field name

**Comment by Vino-S** [comment]
Ready for testing

**Comment by PatReynolds** [comment]
I'm not sure why this is in backlog as it was ready for user testing in January?

I think some decisions have been made elsewhere about the content of individual buttons, that need to be implemented.

**Comment by richpomfret** [comment]
@PatReynolds to review and capture any missing stories from this.

**Comment by PatReynolds** [comment]
Stories #378m #379 and #380 created, this can now be closed.
