### ISSUE TITLE
Add 'technical volunteer' as sole syndicate on transcriber sign up

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#200]
Adding it back is issue #146

**Comment by Captainkirkdawson** [comment]
Have added syndicates. Only one is open that is Technical.  Could I request that @AlOneill and @DeniseColbert both attempt registration as transcribers on FreeBMD2. Let's check that process works as expected. Since this is a test2 site there is a likely an email intercept that comes to me. I will forward

**Comment by AlOneill** [comment]
@Captainkirkdawson Have just tried to register but got the following error:

![FreeBMD-volunteer-issue](https://user-images.githubusercontent.com/14852554/73576372-338c1380-4472-11ea-9b5f-5e1af2e41356.png)

**Comment by Captainkirkdawson** [comment]
What email address please

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by DeniseColbert** [comment]
My attempt returned this:

![image](https://user-images.githubusercontent.com/19173257/74154242-358c6a00-4c0a-11ea-86e9-003718072f9d.png)

**Comment by Vino-S** [comment]
Taking a look at it

**Comment by Vino-S** [comment]
fixed
