### ISSUE TITLE
Implement mobile help/about pages

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#222]

**Comment by PatReynolds** [comment]
Tested 15 Nov 2021 and About Page working fine on pixel XL

Help Page may have an issue - the index is quite a way down the page (below Daisy Dent certificate, above "Getting Started".

**Comment by AlOneill** [comment]
That placement is deliberate on my part — something to read before the "On this page" menu — especially as we have no skip mechanism in place. A screen-reader user will hear the page in the same order as a mobile user will see it. Is that logic flawed?

**Comment by AlOneill** [comment]
That placement also makes the page work left to right on a larger screen — the Shaw Trust called us out for pages that work right to left.

**Comment by PatReynolds** [comment]
The logic isn't flawed, and the idea of some-text-then-index-then-back-to-page is good.  What I think is not good is that intial "some text" is long, and contains information which may be entirely irrelevant to why the person is visiting the help page.  I suggest that only the first paragraph, or perhaps the first two, are read after the title.  Then the index, then the remainder of what is currently the first section (might need its own heading?).

The Alt-text for the two images could be improbed by being what a person will hear on the Entry information page (possibly with some hints and explanation), and what a sighted person reads on the certificate entry.

**Comment by AlOneill** [comment]
@PatReynolds To address the images issue first: the alt text is shown when the image is unavailable for any reason — it was never intended, in the design of HTML, that alt text be used to fully describe an image. The caption is generally where the details should go. I agree that the caption could (should) be expanded to list the fields (or information) shown in the image. "Hints and explanation" probably belong elsewhere.

The source order is trickier. We have to balance the requirement for a page where the tabbing order is left-to-right on a wide screen with the requirement that the page is presented in the order that makes most sense for a screen-reader user or a user on a mobile phone. I can set up the page to our more usual pattern — lead para, sub-menu, the remainder — but we will need a suitable, friendly heading for the content between the lead paragraph and "Getting started" so that a screen-reader user is made aware that it exists. Background? Introduction? "Index information compared with certificate information"? or …??

Maybe the text and images between the lead para and "Getting started" does not belong where it is and should be moved?

**Comment by richpomfret** [comment]
@PatReynolds and @AlOneill to decide upon new order to help with mobile.

**Comment by AlOneill** [comment]
@PatReynolds 
Having ruminated, I suggest the source order should be: lead paragraph, sub-menu, "Getting started", then the remainder of the content.

Suggest we delete the second paragraph (too About) and then re-write and move the third paragraph further down the page. Similarly, the images of the results detail and the certificate belong in the relevant sections further down the page.

What do you think?

**Comment by AlOneill** [comment]
@PatReynolds 
Thinking about `alt` text vs caption: images will need updating (replacing) each time we make adjustments to our layout. They need updating already, now that the presentation of the dates has changed.

If we expand the `alt` text, then a future editor who is tasked with replacing an image would need to be observant and diligent to move any `alt` text rather than simply delete it with the old image — after all it is practically invisible. Out of sight, out of mind.

For the image of the certificate, even a sighted user would probably appreciate reading about the extra details in the `figcaption` because it is not easy to read the text in the image.

So, my vote is to expand the text in the `figcaption`, leaving the `alt` text brief.

Thoughts?

**Comment by AlOneill** [comment]
@PatReynolds I would like to re-order the Help page, as discussed in today's Documentation meeting, but there is already a [DRAFT Help page](https://test3.freebmd.org.uk/cms/draft-help) with edits in progress to the "Further help with family history" section. The yellow `mark` elements there refer to yourself making the edits.

How to proceed? If the edits are complete, then I will re-order that draft page, removing the comments. If not, then we need to decide what to do with the edits as they stand. So, are those edits complete?

**Comment by AlOneill** [comment]
@PatReynolds There is also an untitled section below "Accuracy of FreeBMD"  which talks about Soundex that looks unfinished. Is that also yours and if so what needs to be done there? Thank you!

**Comment by AlOneill** [comment]
Have changed the source order of [DRAFT Help](https://test3.freebmd.org.uk/cms/draft-help) and made some other changes as listed at the top of the page.

**Comment by AlOneill** [comment]
@PatReynolds I see you have added a new sub-section, Good to know about wildcards. This topic is currently covered on More about searching: we need to decide where it best belongs and remove any information that is not correct.

**Comment by PatReynolds** [comment]
I think for testing, we go with the short version on Help (more help won't be available).  I think a bit about wildcard searching in the basic help is good.  May need to link to a longer piece in the more help, but can see with testing.

**Comment by PatReynolds** [comment]
@AlOneill and @PhilipClarke712 this story is not about content (('ve even mislead myself!) so I will move comments re content to the appropriate stories.

This sotry is about how help and about display on mobile phones.  (and may not be needed at all).

**Comment by PatReynolds** [comment]
Both displaying fine on android.  Suggest closing.
