### ISSUE TITLE
Prioritise the Documentation Team's work - mark as MVP 

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#247]

**Comment by PatReynolds** [comment]
@richpomfret and @DeniseColbert do you agree with my prirotisation?

**Comment by DeniseColbert** [comment]
Bumping for my inbox

**Comment by DeniseColbert** [comment]
@DeniseColbert

**Comment by DeniseColbert** [comment]
Should #170 be labelled MVP? It's in a MVP epic.

**Comment by PatReynolds** [comment]
Yes - I've given #170 the MVP phase.

**Comment by PhilipClarke712** [comment]
Hi Pat and Denise,

It’s on my list of “jobs to do” and has been for some months, but (off topic) I have been working on the basis that “Help” pages were a bit higher on my list of “to-do-jobs” than “About” pages. I had always been working on the basis that it was MVP, but when is that?

This task (of page writing) also seems to have several #-numbers associated with it.

I can certainly write an outline of the page, but it will be somewhat different to its FreeBMD(1) predecessor, which used a number of html and Perl pages. Its a bit more complicated than that, because I have no knowledge of what the format of the output or outputs from the FreeBMD2 App or Apps will “look like”. 

Most of the html pages that can be moved across are there in either mostly complete or skeletal form. So, I know what with be “hanging off” that Tab-page.

Is there a date for MVP (I believe at one time it was this Summer), or is it still a bit “fuzzy” still?

Sent from Mail for Windows 10

**Comment by PatReynolds** [comment]
I think the pages are now all marked appropriately, so suggest review at next scrum with a view to closing.

**Comment by richpomfret** [comment]
Appears complete now so closing.
