### ISSUE TITLE
Document transfer of html (incl. cleanup) to Refinery pages

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#251]
From Slack:

As mentioned in the FreeCEN scrum: How to get clean(ish) html from a Google Doc: first download the google doc as html (from the File menu, choose download as ... web page (zipped).  Unzip webpage. Open file in notepad (or similar text editor. Copy and paste into https://www.htmlwasher.com/ Looking at the page I'm working on, I'm going to copy it back into notepad and do some find-and-replace e.g. replace &nbsp with a breaking space, throughout.  do the things that Refinery bucked at earlier (e.g. adding some headers, nesting lists). Then copy and paste into Refinery for final bits of editing.

**Comment by DeniseColbert** [comment]
@ComfE-2662 to take a look

**Comment by PatReynolds** [comment]
Just realised that the code sitting on FreeBMD2 is the mucky code with "dark lord" (or is it "night rider", etc. in. it.

I have made a draft 'how to' on how to check that the page being edited is clean, and how to use the two-third, 1-third structure.  I'll send to @AlOneill for initial checking, ccing @ComfE-2662  for her to see if it is understandable.

**Comment by AlOneill** [comment]
@PatReynolds Sorry, but I'm in a pedantic mind-set and HTML is not code, it is markup. Also, the About page is not typical, the one-third `div` is not generally at the bottom of the page, and it is an `aside` element rather than a `div` element. That About page was not put together by me.

I do not understand what "dark lord" or "night rider" signifies, or what you mean by 'mucky'.

I'm writing a Guide which includes the HTML for the layout: it is pretty close to being ready to put up as a working draft (minus any images). Why do we need a version with errors ahead of the Guide?

**Comment by PatReynolds** [comment]
Sorry for not using the correct words!
'murky' means 'full of bad markup'

Darkrider: sorry - misremembered word is this block of markup:
<style scoped="scoped"> abbr { text-decoration: none; } h2.coloured { color: #895f49; } /* brown-brighter */</style><style class="darkreader darkreader--sync" media="screen"></style>
It has come into  several of our pages, and we've spotted it before but we have not got to the bottom of it.

The 1/2 div is at the bottom of the page because that's where it was where I copied it from.  I sent you the draft just to pick up on such errors ... I had forgotten that you were writing a guide.

**Comment by richpomfret** [comment]
@ComfE-2662 requires access to Refinery before progressing any such stories.

**Comment by AlOneill** [comment]
@PatReynolds That markup, 

"abbr { text-decoration: none; } h2.coloured { color: #895f49; } /* brown-brighter */"

was originally part of a single page on REG. (The unintended consequences of copying … !!) It should be deleted.

The first part prevents Firefox from applying its default styling (which could've changed by now) to abbreviations **in addition to our styling** (weird effect). The irony is that abbreviations, via the `abbr` element are not accessible to keyboard-only users: we no longer use the element on public-facing pages created in Refinery. 

However, the Firefox thing could still be an issue on app pages, maybe only members' pages — I will check (and open an Issue if necessary — It would be easy enough to fix).

**Comment by PatReynolds** [comment]
@AlOneill  could you make a page to go with the guide which has the CSS header/footer and sidebar in place,  with placeholders (e.g. "put title here" for title, "list item 1", "list item" to show how the lists should be laid out)?  that could then be copied within Refinery before being edited for a new page.

**Comment by AlOneill** [comment]
@PatReynolds I _could_ make such a page, a bare-bones template. However, I fear that people would then copy the template and never bother to read the Guide.

The Guide has those lines of markup that a template would have (now beautified!), and these can be copied directly from a browser window.

**Comment by PatReynolds** [comment]
Moved to "in progress" as in progress.

**Comment by richpomfret** [comment]
Done (according to Denise) - closing.
