### ISSUE TITLE
Add number of search limit to exessive search results and Help

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#301]
Number is missing from results page shown if number exceeeded: ![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/47c91c25-b22d-4c75-9bfb-97fdc30983b5) 

Number also needs adding to "Nature of the search" section in Help (currently text is 500, as a place holder.

**Comment by Vino-S** [comment]
Ready for test3

**Comment by richpomfret** [comment]
Thanks @Vino-S, @PatReynolds to take a look and test.

**Comment by DeniseColbert** [comment]
The number is now added in the message but I can't see anything on the Help page (may not be looking in correct place...)

**Comment by PhilipClarke712** [comment]
Hi @DeniseColbert 

You will not find it on the test3 Help page, but it is on test3 in draft form.

Note: when FreeBMD(1) "refuses" to do a search because it is **too big**, it basically removes the middle block of the search page and substitutes  the following text block; 

![Screenshot 2021-05-12 211158](https://user-images.githubusercontent.com/67054943/118038269-ccdcf180-b366-11eb-910c-0587b91ebac5.png)

It's done a Pearl page: https://www.freebmd.org.uk/cgi/search.pl . Its only possible to directly call the search page using this filename (you can't call the error message).

I believe that only one of the three FreeBMD(1) main (general) help pages cover this problem of the search being **too big** : it's in https://www.freebmd.org.uk/search-help.shtml which is called by hyperlink from the FreeBMD(1) Help page. That page is on test3 as a draft https://test3.freebmd.org.uk/cms/help/draft-how-best-to-search and the text can be found in first paragraph of the **Searching the FreeBMD Database.** section. That draft page, I believe was done by Comfort, but it was never progressed beyond what you see; but some of its material was put into the test3 Help page. 

The current test3 Help page does not have any sub-pages, nor any hyperlinks to other FreeBMD2 pages; and it appears to have been made by selecting moving material from Help -subpages on FreeBMD(1) onto what is now the test3 Help page (as mentioned above).

At some point in time a decision will need to be made about enhancing the test3 Help page and deciding what **missing information** should be added to the page directly and what needs to be added via hyperlinks. 

Note: there are quite a few draft sub-pages of Help, but none have yet made it through review (a page with hyperlinks, for example, cannot be sign off until all the hyperlinked pages have been sign off).

**Comment by PhilipClarke712** [comment]
Hi @richpomfret 
 The **View** limit on FreeBMD(1) is stated to be 3000 and that is the same number in the error message I get on test3 if I try and search for: First name = John, Surname=Smith, no limit on dates, "place" nor event. 

That same limit of 3000 is given on the FreeBMD(1) Help page and also appears on https://test3.freebmd.org.uk/cms/help/draft-help-1st-edited-draft-draft  in the first paragraph of the **Nature of the search** section. 

Note: the image given at the top of this story, with no number in the error message, is still the case for test2. But **test3 is OK**.

Out of interest, I started putting limits on my search until I stopped getting the error message on test3, and then slightly relaxed them. I successfully got 2866 births for John Smith between **March 1837** and March of 1843; and 2901 births for John Smith between December 1938 and March 1844. So the 3000 limit is probably what is set on test3.

**Note:** Civil registration with the GRO did not start until six months into 1837, i.e.  the third quarter July-Sept 1837. I don't think there is any easy way of fixing this: there is no data to search for the first six months of 1837, that the search starts with the September quarter of 1837.

**Comment by richpomfret** [comment]
Thank you @PhilipClarke712. @PatReynolds can you comment?

**Comment by PatReynolds** [comment]
Test2: Number of results still missing, e.g. search John SMITH births gives:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/9a11fd7a-b93b-4f0f-a53a-714ac7daaebe)


Test 3: 
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/6f51db95-fa00-4643-8e28-56487924774d)

What is needed is the text (e.g.
Too Many search results  32302 results

**Comment by richpomfret** [comment]
Not necessary to do this update now (as per Pat's last request). Can move back to backlog/future milestone.

**Comment by Vino-S** [comment]
<img width="1499" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGtyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d3d99daab028b5871399cbe26a54617b30a76a3/image.png" alt="image.png" />

**Comment by KristinaGadzhieva** [comment]
Done on test 3 and Beta
