### ISSUE TITLE
Confusion over the use of Magenta (linking and not linking

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#336]
Phillip notes: 

FreeBMD2 test3 is (slightly) different: I need to click on the magenta View button to pull up the Entry information page, then when I click on the magenta page number it displays the (normally) four or eight records - in this case only three (so the 4th might be mis-transcribed or have UCFs).

So, FreeBMD1& 2 both have "live" page numbers that you can click on, but FreeBMD2 test3 does not have that message.

I think there is a bigger problem: you have magenta clickable links mostly on the right hand side of the table; plus the Previous and the Next "arrows"; the Back "button" and the scan file name.

All the entries on the left side of the table are magenta but they are not clickable links, the Title of the page and also the name of the person are magenta but not clickable.

Having had various interesting conversations with Alison on the "whys" of the Guidance: I think that page confuses the user with (fake) magenta lines that are not clickable (or perhaps they are unfinished).

**Comment by Vino-S** [comment]
@Vino-S Remove the Magenta color for the table header

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by PhilipClarke712** [comment]
Hi @Vino-S,  @AlOneill 
Yes that is much improved. The table  has just two magenta entries and they are both linked to a District and a Page, respectively and a magenta button. There are other hyperlinks and buttons in magenta (not all are shown in my screen snip) and they are "active".
![Screenshot 2021-05-25 135024](https://user-images.githubusercontent.com/67054943/119504046-807cb300-bd63-11eb-8c89-2ade1d7efeed.png).

I would comment that the top of the screen shot has "**Entry Information: {name of "hit}**" in Magenta and that does look like a hyperlink, but it is not. This may be a design feature. My preference would be to have that line in default-font-colour, perhaps with the name of the "hit" in bold, but I'm not a page designer, so perhaps Alison or someone more qualified to comment might do so.

**Comment by PatReynolds** [comment]
Hi all, I thought we had made a decision in the scrum on Monday re use of Magenta?  I _think_ we had decided to make links Navy.  Could anyone confirm?

**Comment by DeniseColbert** [comment]
We decided to emulate FreeREG & CEN and use the default grey colour, which Philip has commented on looks good. He suggests that this bit should also be the default grey:

![image](https://user-images.githubusercontent.com/19173257/119657101-66a2a500-be23-11eb-9cd3-2d38b758c3fa.png)

(with the name of the person ("hit") in bold) as it is also not a link. I agree with Philip; this also should be in line with FreeREG & CEN.

**Comment by PatReynolds** [comment]
Hmm. Using dark grey underline to indicate link is fine.  There shouldn't be a confusion with the Entry Information: JOOSEPH SMITH because (a) the line is always there, not just on hover and (b) the line extends across the page.

**Comment by AlOneill** [comment]
We decided in the Scrum that *only* links should be magenta. The discussion around the use of navy was maybe to use instead of magenta on headings that are _not_ links: the conclusion was to use the default colour for headings (table headings and text headings).

@PatReynolds link underlining, which we use for focus and hover, has to the same colour as the link text — that's just how it works.

I agree with Philip and Denise that colour use should be in line with REG and CEN.

**Comment by PatReynolds** [comment]
Thanks for the clarification, Alison.  So changes needed to the H1 on "Results" page and "Entry information" page (I couldn't see magenta being used anywhere else in a header).

**Comment by richpomfret** [comment]
@AlOneill can you confirm what Pat has said before Vino implements?

**Comment by AlOneill** [comment]
I can confirm that there is a visible page `h1` on the Results page and that the magenta colour comes from the class `project-text-color`: this class should be removed.

However, on the Entry information page, what looks like it should be the `h1` is actually a paragraph: it also has the `project-text-color` class, which again should be removed. (There is an `h1`, however, which is not visible. Why is the markup so convoluted?)

If there are other magenta headings (or pseudo-headings!), I guess they will also have the `project-text-color` class.

I find other aspects of the the markup on the Entry Information page puzzling: the effect of selecting an 'option' is so far from the cause (the select box) that I initially missed the link to the scan; the space for the advert encroaches on the space for the table; I do not think that the second "Report an error …" button should be within the table.

Should the name be rendered as title-case for the forenames (rather than upper-case) and then upper-case for the surname?

**Comment by richpomfret** [comment]
@Vino-S to make additional change as per Alison's last question (Pat confirmed).

**Comment by Vino-S** [comment]
Made ammendments in test3

**Comment by AlOneill** [comment]
@Vino-S 

The Results page still has a magenta heading (that is not a link):

![results.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/6cbbddce-242c-4202-b148-e092539fc917)

I will continue to take note of any others.

**Comment by PatReynolds** [comment]
This issue is on you, @AlOneill but I think it is currently an action for @Vino-S - please correct me!

**Comment by AlOneill** [comment]
@PatReynolds All I can do is comment: @Vino-S is the one who makes things happen.

BTW, the "Results" heading is still magenta.

**Comment by Vino-S** [comment]
Fixed Results header color in test3

**Comment by DeniseColbert** [comment]
@PatReynolds tested, looks good, please puch to beta @Vino-S
