### ISSUE TITLE
Investigate the variation of casing of Names in FreeBMD

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#387]

**Comment by PhilipClarke712** [comment]
Hi @PatReynolds

I suggest, from the title of this story, that you have self-assigned an investigation into the wrong question. 

The question should be: "**does FreeBMD2 normalise the case of the name-data it pulls off the data-base**"; and that is a system design question. Not that I have ever seen the data-base - so this one might bite me.

I strongly hold the oppinion that FreeBMD(1) does not normalise the case of name-data. 

As a transcriber, I sometimes have to do corrections and that involves sending a new version of a CSV-file to the system, so I know what is on my CSV files (and those have the same case as what the system displays when a search is carried). 

"Strictly", the type-what you see (TWYS) rule for case applies; and for those periods in which the GRO published handwritten-, type-set / (printed)- and typed- indexes, everything was in Sentence-case. The case in modern computer-generated GRO indexes (incuding COM) changed to Caps-only, or at one time Caps-only for the Surname. Syndicate rules can over-ride the TWYS case rule (and some transcribers might choose TWYS over syndicate). 

Note: I find it harder to check caps-only names, so I have a preference to use sentence-case, which is great when the GRO uses sentence-case. 

GRO Late Entries, were initially handwritten in Sentence case, so they could well be Sentence-case entries on a Caps-only index page.

Certain family history societies, including those I belong to, use bold-Cap-Case for Surnames, to make them stand out, but they can't impose that onto the GRO.

FreeBMD has a policy of independant-syndicates double-keying records (with some gaps) upto  currently about 1908. So, any record before, say, 1910 is likely to be double-key and the individual matching-pairs may be non-indentical in respect of letter-case. That is obvious from a FreeBMD(1) search. 

The FreeBMD data-base has the ability to ignore case during the search, but FreeBMD(1) displays what the data-base holds in the case that matches the transcribed entry.

So, the question is what does FreeBMD2 do with its "hits", does it normalise case, or does it show what it gets from the data-base.

**Comment by PatReynolds** [comment]
@AlOneill or @DeniseColbert can you remember what this task was about - I think it arose from an error introduced by formating in FreeBMD2 (Emily daisy DENT where FreeBMD1 has Emily Daisy DENT).

**Comment by AlOneill** [comment]
@PatReynolds We noted in the Scrum that there is no consistency in the presentation of names wrt casing and Philip confirms that this is the result of inconsistency in the GRO Index itself, the instructions to transcribe 'as is' and syndicate instructions that might or might not over-rule the original instructions!

Whilst the wish to transcribe exactly 'as is' is understandable, do we need to be consistent in our casing of names in Results and Entry Information? Should we follow the convention of title case for the forename, upper-case for the surname, in what we show a researcher?

REG definitely enforces the convention. I cannot remember for certain what CEN does, but think it does (or did!) enforce the convention.

**Comment by PhilipClarke712** [comment]
@AlOneill ,

It's a lot more nuanced than that, there is GRO consistency based on the technology employed at the time, but it changes over time: Handwritten, Printed (Typeset) up to I suspect WW I , Typed, up to I suspect 1950s, and then to computer generated. An otherwise consistent page, may have Later Entries that are inconsistent. Any given year or period should be consistent on the basis of TWYS, but duplicate entries by different syndicates may be inconsistent. Syndicates or individual transcribers may be inconsistent.

There should be no **forenames** starting with lower case letters: they will start with a Cap and continue in lower case; or modern ones with be all Caps.
For the majority of the time (Typeset) **surnames** were all Caps; and Modern indexes are all Caps, but at times they will start with a Cap and be in lower case.

Looking at **Edith Daisy Dent** on FreeBMD(1) the GRO Index for both her birth and Death are in Typeset pages in the form **DENT, Edith Daisy**. These two events were transcribed by two different transcribers (so four records), for each event they typed the surname as **Dent**, not DENT.

The test3 results page is a faithful reproduction of what the transcribers typed in respect of case; but the two Entry information pages appears to use case-switching to make the surname all-caps (which coincidentally is what the GRO published). The same is true of Beta. I can't find "daisy", its always Daisy for this person; so Edith daisy Dent/DENT must have been a case-switching glitch in respect of "**daisy**".

I have nothing against forcing the surname to be all caps - but if we do that then the Results page and the Entry Information page should be consistent. 

Searching BMD1 births for Dent between 1888 and 1900 (to keep the hit rate below 3,000) it has far more **Dent's** than **DENT's**, so the transcribers appeared to case-switch what the typed and it does look a bit messy. I would probably transcribe it as Dent, rather than DENT, Over this period the GRO used **DENT**. 

If I'm searching, I suspect that a change of surname in a long list is a bit more obvious in all Caps; but when I'm checking all caps is a bit harder to do than name-case.

**Comment by PatReynolds** [comment]
I have not spotted a miscasing (as opposed to true transcriptions of the various casing styles used over the years by the GRO) for some time.

Edith Daisy Dent is now properly cased, so suggest closing

**Comment by richpomfret** [comment]
All working fine, closing.
