### ISSUE TITLE
Report a Data Problem- Answers snag list

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#398]
I will populate this when layout story is complete, as there may be some overlap

**Comment by richpomfret** [comment]
@DeniseColbert to add snags.

**Comment by richardofsussex** [comment]
Once the revised text for #397 is agreed, please action this story.

**Comment by richardofsussex** [comment]
I think we should make a decision on what counts as a useful correction to the data, and adjust our wording accordingly. My own view is that we should only encourage the addition of information which relates to the accuracy (or otherwise) of the GRO index entry itself, as a pointer to the GRO Register. For example, if someone selects "The District is not the place where the person was born, married or died", they should be told that this is information which should be recorded in their own (or someone else's) genealogical record for the person, possibly in a shared free online resource such as WikiTree, and _not_ placed in a postem.

**Comment by KristinaGadzhieva** [comment]
The MVP implementation is addresed in #397. I think this story can be closed. @richardofsussex do you agree?

**Comment by richardofsussex** [comment]
Yes, let's move on ...
