### ISSUE TITLE
Records page: add warning 

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#459]
Having now looked at https://beta.freebmd.org.uk/districts/677/details-of-basildon-district?locale=en I think the best place for the warning is above the link to UKBMD.

Draft: https://docs.google.com/document/d/1-sn0nSbAlQmC1R-shggFu6CmoXo7I8RPlkU2lHrYpuU/edit?usp=sharing

**Comment by PatReynolds** [comment]
Is this ready for implementation?

**Comment by richpomfret** [comment]
@DeniseColbert to review.

**Comment by DeniseColbert** [comment]
I think the text could be tweaked for clarity- adding to the Doc Team agenda...

**Comment by DeniseColbert** [comment]
@Vino-S could you please change the text in the final row to this:

There is  more information about Bakewell (1839 onw) on the UKBMD website.  
Please note that during the period this Registration District name was used there could be changes in which places were included within the district.  UKBMD  includes information on these: 
[More information about Bakewell (1839 onw) on UKBMD](http://www.ukbmd.org.uk/reg/districts/Bakewell.html)

So that it looks like this:
![image](https://user-images.githubusercontent.com/19173257/154084549-a05f64e7-5a4a-4bf2-b017-a6b279da974a.png)

(the text is also on the document in the story description)

**Comment by AlOneill** [comment]
@DeniseColbert @Vino-S 
As the link in the last line is to an external site, it should open in a new tab and there should be a warning in the link text:
More information about Bakewell (1839 onw) on UKBMD (opens in new tab)

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by AlOneill** [comment]
The text ' (opens in new tab)' should be part of the link-text, unless we are moving on … ?

**Comment by PatReynolds** [comment]
' (external link)' should be part of the link text

**Comment by richpomfret** [comment]
@Vino-S can you update as appropriate (as per Pat's comment about putting in 'external' link). Please ask for clarification if required.

**Comment by DeniseColbert** [comment]
@Vino-S to review

**Comment by DeniseColbert** [comment]
Documentation team to check this is OK

**Comment by AlOneill** [comment]
@DeniseColbert 
II am a little confused — on beta and test3, the current UKBMD line in the District Info table is, for instance:

![FreeBMD-district-info.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/26f39906-a50c-4aa7-8779-55ecef8bb931)

So:
* do we make the link open in a new tab?
* if so, the warning should be re-written and made part of the link text itself — " (opens in new tab)"
* if not, the text surrounding the link needs cleaning up

I note that the contents of the `title` element (and hence the browser tab label) is "FreeBMD |" which is not correct — it should be "District Information: Machynlleth | FreeBMD". This applies to test3 and beta. Plus the preceding pages should also have `title` elements with more helpful (i.e. specific) contents.

**Comment by DeniseColbert** [comment]
The way we treat links has changed since this story was created, so I'll close this story and make a new one.
