### ISSUE TITLE
Change Unique Names to Names

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#470]

**Comment by AlOneill** [comment]
There are no instances of the word "unique" in any of the published Help or About pages on test3.

Looking at the Records section, the word "unique" appears to have been removed from the displays already.

![FreeBMD-district-info.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/a375686e-964d-42be-a7f1-6f77a4893cd3)

![FreeBMD_names.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/859aebad-925d-4144-bc4d-44ab9c1960a3)

Unless there are other places to look, then this issue is fixed.
