### ISSUE TITLE
Expired FreeBMD1 URLs to redirect to FreeBMD2 website

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#508]
Relates to #384

**Comment by richardofsussex** [comment]
If the 'pretty' version of the URL is used, it contains sufficient information to construct a search for that record. If the search succeeds in finding the (edited) record, we can find the UUID it now has. Then all we have to do is to put an entry in a lookup table, mapping old UUID to new UUID. Subsequent lookups can use this mapping to go directly to where the record now lives.

**Comment by richardofsussex** [comment]
Correction to above: I don't think I read the issue title carefully enough (and there is no supporting commentary). Please read this following comment, and let me know if I am now actually addressing the issue (!)

If by an "expired FreeBMD1 URL" we mean one which was allocated by a previous iteration of the BMD database, and which is no longer valid, then I think this requirement cannot be met. The hash within the BMD1 URL is based on a number of data fields within the record, but it is like an omelette: you can't reverse engineer it back into the eggs from which the omelette was made.  If a user has saved only the BMD1 URL, and that URL is no longer valid (because the record's data has changed), then their only recourse is to remember and re-run the search which yielded that URL in the first place. BMD1 does provide a facility for saving search logic locally.

Conversely, if the requirement is for saved BMD1 URLs to resolve to the corresponding record on the BMD2 site, then that is worth implementing for those cases (the vast majority, I would guess) where the data of that record has _not_ been updated since the BMD1 URL was minted. I just tried picking up a hash value from the BestGuessHash table in my BMD2 test data and injecting it into the BMD1 URL pattern:
https://www.freebmd.org.uk/cgi/information.pl?cite=ippW6bzRyBXCEizl5zo8RQ&scan=1
This resolves happily within the BMD1 site. However, taking the same hash and injecting it into a BMD2 URL _doesn't_ work. The Record Detail page for the corresponding record has the URL:
http://localhost:3000/63459192da0bc459b84137ad/entry-information/46/maria-abbott-birth-blaby-v15-p47?locale=en&search_entry=46

Once we have switched the domains over, so that the freebmd.org.uk domain resolves to the BMD2 Rails-powered site, then we will need a Rails route which tackles the BMD1 URL pattern. However, we can develop and test this route within the BMD2 development environment prior to the switchover, by using a hybrid URL, e.g.:
https://test3.freebmd.org.uk/cgi/information.pl?cite=ippW6bzRyBXCEizl5zo8RQ&scan=1
The hash needs to be picked out of this URL and used to find the RecordNumber (in the BestGuessHash table). Once we know the RecordNumber, we can generate an Entry Information page for that record. Whatever form of URL that Entry Information page ends up getting (and we haven't yet decided that) will be, in effect, the Persistent Identifier for that record. I don't think it will be the same as the BMD2 URL example quoted above, because (as I understand it) that URL relates to the search results within which the record sits, as well as to that individual record.

**Comment by richardofsussex** [comment]
OK, I have now developed a routing system which takes a URL like:
http://localhost:3000/cgi/information.pl?cite=ippW6bzRyBXCEizl5zo8RQ&scan=1
where the cite parameter is one of our hashes, and maps it to:
http://localhost:3000/entry-information/id/?record_id=46
which delivers the detailed page for that record. When we switch over to making BMD2 the default user of our freebmd.org.uk domain, this mapping will automatically pick up saved BMD1 URLs like:
https://www.freebmd.org.uk/cgi/information.pl?cite=mD775lQiYFgX0iO%2FRV16OQ&scan=1
and display the relevant record.
![image](https://user-images.githubusercontent.com/2197102/195588231-933922ad-08fd-46d6-ad0f-f257f40c9dcb.png)

Having established the technique, we still need to decide what form we want the redirected URLs to have. Although I currently map the hash value to a Record Number, I think on reflection that the hash value has more permanence than the record number (which is specific to the current iteration of the BMD database, i.e. it's not permanent at all). So we could have something like:
https://www.freebmd.org.uk/entry-information/mD775lQiYFgX0iO%2FRV16OQ/hash
as the persistent URL. Any other suggestions?

**Comment by richardofsussex** [comment]
Implemented that, and added a redirect back to the search page when the hash is not found in BestGuessHash:
![image](https://user-images.githubusercontent.com/2197102/195633064-11408e63-8437-4ab1-8b43-3e1153a174b9.png)

**Comment by richardofsussex** [comment]
Simple "Hello world!" experiment with Linked Data for these URLs, using content negotiation, worked first time (!!):
![image](https://user-images.githubusercontent.com/2197102/195641800-d7d25bee-670d-4067-a72c-e0df1564b248.png)
and:
![image](https://user-images.githubusercontent.com/2197102/195642189-f17a5f89-ed64-448c-8173-f014e3f8f7b5.png)
These are just dumps of the selected record in XML and JSON serialization, but they correctly respond to the Accept header in the HTTP request, and suggest that we could develop something more sophisticated if required.

**Comment by DeniseColbert** [comment]
This seems to be moving along the right lines, from my understanding, Richard, thank you! I think Vino's input would be most useful as she understands the database, but I would say that the way we present the URL may impact the Citation generator so that should be taken into account.

**Comment by richardofsussex** [comment]
OK, on advice from Vino I have refactored and simplified the code. The check, for the hash still being valid, now takes place _after_ redirecting to the BMD2 form of the URL. We need to build on this, by supporting users who save our new 'friendly' URLs, to cope with the situation where the hash _they_ contain is no longer valid. Because the 'friendly' URL contains the search parameters, it should be possible to reconstruct the search and populate the initial search page with those values.

**Comment by DeniseColbert** [comment]
@Vino-S to bring over to test3

**Comment by DeniseColbert** [comment]
@Vino-S to check this is in Test3 and let Richard know.

**Comment by DeniseColbert** [comment]
ready for @richardofsussex to test on Test 3

**Comment by richardofsussex** [comment]
Taking a saved URL from my WikiTree records, and changing 'www' to 'test3', it successfully redirects to the relevant page where the hash is still valid:
![image](https://user-images.githubusercontent.com/2197102/217530062-9bcb3bf6-c1c3-45a9-a33e-e554019548a6.png)
Where the hash is not valid, it redirects to the 'page not found' page:
![image](https://user-images.githubusercontent.com/2197102/217530432-0db4e021-c006-49a3-aadf-670ce17db877.png)
I suggest we deploy this to beta, close this story and start a new one to pick up the 'page not found' error and replace it by something more helpful.

**Comment by richardofsussex** [comment]
Actually, since this particular URL doesn't have the 'friendly add-ons' at the end, it's not possible to reconstruct the search from the hash. All we could do is to output a more specific error message, saying the data has been altered and they will have to re-run the search. (This could include taking them to the search page.) However, we should still have a story to implement proper support, i.e. populating the search criteria, where the 'friendly add-ons' _are_ present in the URL.

**Comment by DeniseColbert** [comment]
@Vino-S to deploy Beta

**Comment by DeniseColbert** [comment]
Done, closing
