### ISSUE TITLE
Surname in Names (Yeovil) not present in any of our databases

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#525]
Did a search for Brattonsaggs in Test, Beta and FreeBMD1 but no results. Was this a correction that hasn't found its way into Names yet, or a sign of something else?

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/35f31f51-09f1-433e-87aa-d52cd610cb68)

**Comment by richardofsussex** [comment]
There are two Bratton-Saggs entries for Yeovil, which suggests that the processing that generates the table of unique names is conflating this into a single 'name'. This means that '-' should be treated as a word separator during this process.

Another issue that was raised in this context is the doubling-up of some names in the list. This is quite common, and I suspect that names are not being case-folded before being checked for uniqueness, so that 'SLOAN' leads to one entry and 'Sloan' to another (both being presented as 'Sloan').

**Comment by DeniseColbert** [comment]
Great sleuthing! Would you be able to look at the fixes for this or would you prefer Vino to do this?

**Comment by richardofsussex** [comment]
I think Vino is better-placed than me, because this relates to the separate rake task which generates the unique names data. However, if she doesn't have time please assign it to me.

**Comment by DeniseColbert** [comment]
@Vino-S could you take a look please?

**Comment by DeniseColbert** [comment]
Is it a multimodal issue?

**Comment by DeniseColbert** [comment]
@Vino-S to add a comment so that @richardofsussex can look further

**Comment by Vino-S** [comment]
Brattonsaggs: is Mother's surname
Bratton-Saggs: I cannot find Bratton-Saggs in Yeovil. 
However I looked at  Bratton-Saggs in other districts for example in St. Alban's, it is displayed as: Bratton Saggs. So the hyphen is removed. 
Casing of the names in front end is causing the issue. Can be fixed quickly

**Comment by DeniseColbert** [comment]
@DeniseColbert to test on Test 3

**Comment by DeniseColbert** [comment]
Tested, looks fine: closing
