### ISSUE TITLE
Autocomplete for District and Counties

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#553]
Suggestion:

County shouldn't need to be selected for a district search

District field should be populated per BMD1 and typing should contract results so user can select from pool of results

**Comment by richardofsussex** [comment]
The request is for, in effect, a multi-select drop-down with autocomplete filtering. I'm not sure that's even achievable. I'm pretty sure that it's not supported out of the box by Rails. @Vino-S can confirm or refute this opinion, please. (Autocomplete is designed to help users select a single entry for a text input box, and the input box itself is used as the place to put what the user types. If instead it's a selection list, it's not clear where you would put that information.)

At present, the districts for each county you select are dropped into the Districts selection box, with a helpful county heading. One thing we could do relatively easily (I think) is to initially populate Districts with a full list in that format, i.e. grouped by county, rather than leaving it empty as we currently do. Then, selecting a county would cause the District list to contract to just those for that county, as it does at present.

**Comment by richardofsussex** [comment]
I have managed to get it to display a full alphabetical list of Districts when no County has been selected. This will therefore be how the page appears initially. This is comparable to what BMD1 offers. @Vino-S please see branch fb_533_rbl (which also contains some extraneous files from my attempts at autocomplete for dates - these are not required). Maybe push this version for testing, and consider whether we can do any better, given the complexity of the selection controls and the need to support multi-select.

**Comment by richardofsussex** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWMwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--41a777f0b36ccda2d4bd2d85c9c46f43cccf59b7/image.png)

**Comment by KristinaGadzhieva** [comment]
For consideration: to implement autosuggest with multiple selection. 
Something similar is described here: https://medium.com/@sherzelsmith/add-a-filtering-multiple-tag-system-with-autocomplete-to-your-rails-model-in-rails-5-1bf88cd53e9
Vino thinks we can try implementing it. @AlOneill Alison, please have a look, we would like to know your thoughts on it.

**Comment by AlOneill** [comment]
I guess you are asking if such a model would be Accessible — I have no idea without something to test. Sorry.

**Comment by DeniseColbert** [comment]
@Vino-S to develop something for Alison to test

**Comment by richardofsussex** [comment]
@vino-s working on a plain javascript implementation of this functionality

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by richardofsussex** [comment]
County, when selected, doesn't make it into the search criteria. If you select a District within the county, that _is_ added to the search. However, when you go back to modify the search, neither the County nor the District input box is populated with the previously selected values.

**Comment by KristinaGadzhieva** [comment]
Tested on test 3. Now when I select "Revise search" and go back, only County is populated with the previously selected values, no districts data is saved.  Morevover, in order to select Districts again, I need to reselect Counties and only then I can choose Districts.
The issue still needs to be fixed.

**Comment by Vino-S** [comment]
In progress

**Comment by KristinaGadzhieva** [comment]
Ready for testing
