### ISSUE TITLE
Add a "Get help with searching" link at the search page

### ISSUE THREAD

**Issue by KristinaGadzhieva** [FreeUKGen/FreeBMD2#560]
The Help link in the navigation takes Researcher and Members to Search Help page.

**Comment by richardofsussex** [comment]
Need to rename the existing menu item to "Search help", and have it always appear. The menu item "Help" (which goes to the non-existent help for administrators page) needs only to appear when the user is logged in.

**Comment by richardofsussex** [comment]
Search help will link to the existing help page for searching.

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by richardofsussex** [comment]
Yes, the Help menu item now links to the general Help page, which is a big improvement. It is still called "Help", rather than "Search Help" as suggested, but the help page contains information on all aspects of searching, results pages, ordering certificates, etc., so on reflection I'm happy for it to be called just "Help".

**Comment by DeniseColbert** [comment]
@KristinaGadzhieva the help link on the navigation menu bar now works as expected but is this story about placing a reminder on the search page/form that there is help available?

**Comment by KristinaGadzhieva** [comment]
Ready for deployment

**Comment by Vino-S** [comment]
Deployed
