### ISSUE TITLE
Consider implementing bootstrap CSS styling 

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#80]
Vino reports that constructing the dropdown menus will be much easier. It's preferred to start a new project rather than use multi-modal code as there would be styling conflicts when bootstrap is implemented.

**Comment by DeniseColbert** [comment]
Also, if we are to implement the mobile layout as per wireframe in drive, bootstrap is necessary.

**Comment by Captainkirkdawson** [comment]
I am sorry to hear of this and its suggestion that **we abandon the multi modal concept** and all of its benefits. Such a step has MAJOR implications and should be based on a fundamental rethink of our whole implementation approach not as a byproduct of a single issue.  It would also make the use of BMD2 improvements impossible without rewrites of CEN and REG.

**Comment by DeniseColbert** [comment]
@Captainkirkdawson only Vino and I were at the FreeBMD2 scrum and I noted down her observations for consideration and discussion at the next meeting. I'm not sure I've noted them faithfully as I don't **think** Vino was suggesting we abandon multi-modal, but again, I could be wrong.

**Comment by Vino-S** [comment]
@Captainkirkdawson 
Moving into the new design, needs lot of hard coding changes and more line of codes can be reduced by the bootstrap and everything else including the multi model system is going to be the same. So all I am proposing to use the bootstrap gem and a custom style to replicate the new design. Abandoning the multi model system is a big move and I am not thinking of that

**Comment by Captainkirkdawson** [comment]
I am sorry if I have overreacted but the story clearly said `It's preferred to start a new project rather than use multi-modal code' that to me was quite clear in its meaning

**Comment by Captainkirkdawson** [comment]
@vino @DeniseColbert I remain TOTALLY unclear on the issue that is pushing for a new project.
The current MyopicVicar displays are constructed from 3 partials and a page yield. The 3 partials are Header, Navigation bar, and Footer. The changes proposed to these partials are trivial and can be implemented with little effort. The page yield part is the "guts" of the display from a user perspective. All our displays use the same Header, Navigation bar and Footer and these are multimodal. The specific content displayed depends on what "view" is being displayed. That can be a search_query_form or any other view. What is being suggested for the BMD search page is similar to REG and CEN but with only ONE change and that is the use of drop down menus.  Surely that does not require us to throw out our whole design from the past 4 years? The use of a gem for drop down menus may be useful (I have not researched the requirement) but I see no reason why that cannot be done within the current structure.

**Comment by Vino-S** [comment]
@Captainkirkdawesson
The old layout needs a lot of modifications to get to new design. For example moving of site icon to the nav-bar alone needs lots of css style changes. We going to give new face for FreeBMD, I think it would be better to start as a new one instead of messing the existing styles. It would also be easy for making the new layout multimodal. It will also be helpful if want to make cosmetic changes to our site in future. Also we are using a lot of static HTML code in our erb files which needs to re-written in conventional Rails.

However, I can work with existing styles but I think it will be much easier and cleaner for me to go with the new assets by using the current multi modal work flow,

The main reason is, to install the boostrap gem to the current system might conflict with the current grid system we are using but this is my thought and am open to suggestion.

**Comment by richpomfret** [comment]
@Vino-S as discussed, we are putting bootstrap on hold until much later on in order to be able to reuse the current multi-modal code and speed along towards the MVP. At that point, we can review and look to roll it out on our other projects at the same time.
