### ISSUE TITLE
Respace search page (and other pages) (on site)i n line with FR2 and FC2 feedback

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#9]
requires #2
requires #13
needs #51

**Comment by PatReynolds** [comment]
May need change after testing on cloud9

**Comment by avielbassalian-freeukgen** [comment]
This sounds like it's very similar modifying white space, if not the same. It might also be a parent task.

**Comment by PatReynolds** [comment]
@DeniseColbert to send Aviel and Neslihan the feedback on FreeCEN spacing

**Comment by richpomfret** [comment]
Denise has sent this. Next step = @neslihanu to take a look at this (no need to review everything as it is rather large - but search for keywords e.g. space issue/white space etc).

**Comment by neslihanu** [comment]
The feedbacks on FreeCEN spacing has checked (searched for keywords "space" and "white space"). Please find the comments/feedbacks below;

1.) I prefer the old style. Too much white space!
2.) too much white space in background - old format easier to read and faster to input details - I'd prefer the older format to be restored.
3.) FAIL. Bring back search by street function. Page is too spread out/too much white space - search used to fully display in window without having to scroll down to complete search. Hand pain is real - don't make things require MORE movement than previously.
4.) Too much white space -   please compact it.


1.)I consider that the page where one inputs one's search parameters is far too spread out. It would be far easier to use if it was condensed so that there was not so much space between the various sections.  It would also be easier to use if the name input section followed the example of the majority of other similar sites and one entered fore-name followed by family-name.  Your converse way of entering the names caught me out several times.  It is not as though one was in the army!
2.) We seem to have lost the ability to include occupation in the search, which is a big drawback. Also, the sorting function for results does not work - for example I've just tried to sort on county of birth in the results page, and I get a different order from the original, but nothing remotely resembling an alphabetical sort. Even allowing for additional spaces at the beginning of entries the results are in no apparent logical order 
3.) I like the new web site. I like the fact that it is easier to use than FREECEN1 and that the input form is very similar to FREEREG. I don't really like the FREEBMD format it's not intuitive. not much space right here for more comments, happy to share further thoughts via email.

Although the comments do not give too much details about the users concerns, according to the feedback's the main issues can be listed as below;

1. User has to scroll down to complete the search form. 
2. Search fields are too spread out. 

We have already changed the search form/ search page layout, according to the new layouts user do not have to scroll down to complete the search form and the search fields are close to each other. Additionally the background of the search form has changed.

**Comment by richpomfret** [comment]
Closing - complete for 1st iteration. Ready now for Vino to implement.
