### ISSUE TITLE
Create HTML Records page (was Link from FreeBMD2 Records page to FreeBMD1 Records page)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#97]
Page called 'coverage' or transcriptions'now standardised as 'Records' in order to make it clearer to the users what the focus of the page is.

**Comment by PatReynolds** [comment]
Link now Transcriptions tab = Link to https://www.freebmd.org.uk/progress.shtml Is this complete, or do we want an intermediate page, possibly with links to other pages?

**Comment by PhilipClarke712** [comment]
It was my intention that the current Transcriptions tab on test2 be replaced by this Page: 
https://test3.freebmd.org.uk/cms/draft-transcriptions

**Comment by PatReynolds** [comment]
Hi @PhilipClarke712 belatedly updating this story to indicate a new name for this page, and clarify its use. These pages are created by developers and pull information from the databases, hence at the moment simply pointing at FreeBMD1.

See:
https://www.freereg.org.uk/freereg_contents/new?locale=en
and https://www.freecen.org.uk/freecen_coverage?locale=en

The plan for MVP is now to simply link the tab to FreeBMD1.

I think some of your pages will need to link to About or Help (or both) either/and as well as to the main Records page.





'

**Comment by PhilipClarke712** [comment]
Hi @PatReynolds,

Thanks. I have a such page fairly closed to completion, but it will not have a full set of completed sub-pages, because some of these will be implemented as programming. 

I have also been talking to Alison about putting some of these draft-pages forward for review. Meanwhile, I will rename my Draft-Transcriptions page to Draft-Records. 

There are links to some Help sub-pages, including the search-FAQ's and some of the About sub-pages, but not to sections within those two top-level pages.

Sorry, I did not read the comment above correctly, so my points here are no longer valid. I do have a page in draft-form but it is not yet complete. It will be very different to the FreeREG & FreeCEN looks and it will not be ready for MVP, since none of its sub-pages are complete **and** signed off.

**Comment by Vino-S** [comment]
ready for testing in test2

**Comment by richpomfret** [comment]
@richpomfret to test.

**Comment by richpomfret** [comment]
Tested and works as expected (takes user to FreeBMD1 coverage charts page). However, to review whether this is satisfactory - it is bad practice for a header or title menu option to take a user out of the website. Rather this should be a page where the user is given a brief summary for their understanding and then provided with a link (open in a new tab) which takes them over to FreeBMD1). To discuss.

**Comment by PatReynolds** [comment]
Make an intermim page @PatReynolds to write text.  Linked page opens in a new tab.

**Comment by PhilipClarke712** [comment]
Hi @richpomfret  @PatReynolds 
 I have such a page https://test3.freebmd.org.uk/cms/draft-coverage which was put onto Refinery towards the end of last year. 
 
It also includes sections on the GRO and Civil Registration  and Civil Registration Districts, because it was my understanding last year that they were within its scope.  I've been more recently informed that  this might not be the case.

If Pat regards the page as a good starting point, the links to FreeBMD(1) could be put in almost straight away.

**Comment by AlOneill** [comment]
The [Draft Records]("https://test3.freebmd.org.uk/cms/draft-records") page has been created on t3.

@PatReynolds @richpomfret Is this what you had in mind? Does the page need anything else? Did your (Pat) draft text include anything else?

**Comment by PatReynolds** [comment]
Thanks, @AlOneill that is what I wanted.

**Comment by AlOneill** [comment]
@PatReynolds So I guess the next steps are to promote page name to "Records" — done! — and then ask @Vino-S to replace current link in main menu, to BDM1, with link to /cms/records ?

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by AlOneill** [comment]
Works as expected. Thanks, @Vino-S
